from pyzoe.definition.register_names import *
from pyzoe.definition.register_values import *

modbus_map = {
    device_communication_status_n: device_communication_status,
    emu_status_n: emu_status,
    emu_boot_ver_n: emu_boot_ver,
    emu_s_ver: emu_s_ver,
    emu_h_ver: emu_h_ver,
    history_year_month_n: history_year_month,
    history_day_hour_n: history_day_hour,
    history_minute_second_n: history_minute_second,
    history_systick_n: history_systick,
    history_pcs_charge_energy_n: history_pcs_charge_energy,
    history_pcs_discharge_energy_n: history_pcs_discharge_energy,
    history_battery_charge_energy_n: history_battery_charge_energy,
    history_battery_discharge_energy_n: history_battery_discharge_energy,
    operation_datetime_n: operation_datetime,
    operation_status_tag_n: operation_status_tag,
    operation_event_description_n: operation_event_description,
    serial_number_n: serial_number,
    soc_n: soc,
    pcs_running_state_n: pcs_running_state,
    board_serial_number_n: board_serial_number,
    grid_frequency_n: grid_frequency,
    battery_communication_status_n: battery_communication_status,
    battery_cluster_total_voltage_n: battery_cluster_total_voltage,
    battery_cluster_total_current_n: battery_cluster_total_current,
    battery_cluster_soc_n: battery_cluster_soc,
}